#!/usr/bin/env bash

RECORD_DIR="$HOME/Videos/Recording"
RECORD_PID_FILE="/tmp/ffmpeg_screenrec.pid"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
FILENAME="$RECORD_DIR/recording_$TIMESTAMP.mkv"

mkdir -p "$RECORD_DIR"

start_recording() {
    ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i "$DISPLAY" \
           -f pulse -i default \
           -c:v libx264 -preset ultrafast -c:a aac -y "$FILENAME" > /dev/null 2>&1 &
    echo $! > "$RECORD_PID_FILE"
}

stop_recording() {
    if [ -f "$RECORD_PID_FILE" ]; then
        kill "$(cat "$RECORD_PID_FILE")" && rm "$RECORD_PID_FILE"
    fi
}

is_recording() {
    [ -f "$RECORD_PID_FILE" ] && ps -p "$(cat "$RECORD_PID_FILE")" > /dev/null
}

case "$1" in
    start)
        if ! is_recording; then
            start_recording
        fi
        ;;
    stop)
        stop_recording
        ;;
    status)
        if is_recording; then
            echo "󰑊  Recording"
        else
            echo "  Record"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac
